[package]
name = "dustbox_frontend"
version = "0.1.0"
authors = ["Martin Lindhe"]

[[bin]]
name = "dustbox-frontend"
path = "src/frontend-main.rs"

[dependencies]
clap = "2.33"
sdl2 = { version = "0.32", default-features = false, features = [ "gfx" ] }
dustbox = { path = "../" }
