language: rust
cache: cargo
sudo: required
dist: bionic

matrix:
  fast_finish: true
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: stable
    #- env: TARGET=x86_64-unknown-linux-gnu
    #  rust: nightly

install:
  - sudo apt-get install -y libgtk-3-dev libsdl2-dev libsdl2-gfx-dev libegl1-mesa-dev libgles2-mesa-dev nasm
  - ndisasm -V
  - cd .. && git clone --depth 1 https://github.com/martinlindhe/dos-software-decoding && cd -

script:
  - cargo build --all
  - cargo test --all
