language: rust
sudo: required

matrix:
  fast_finish: true
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: stable

install:
  - sudo apt-get install -y libgtk-3-dev libsdl2-dev libsdl2-gfx-dev libegl1-mesa-dev libgles2-mesa-dev
  # this is the most recent nasm ubuntu version that is not xz compressed, as xz compression is unsupported by Ubuntu Trusty (14.04) used in Travis
  - curl -O http://archive.ubuntu.com/ubuntu/pool/universe/n/nasm/nasm_2.13.01-2_amd64.deb && sudo dpkg -i nasm_2.13.01-2_amd64.deb
  - ndisasm -V
  - cd .. && git clone https://github.com/martinlindhe/dos-software-decoding && cd -

script:
  - cargo build --verbose --all
  - cargo test --verbose --all

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo
