[package]
name = "dustbox"
version = "0.1.0"
authors = ["Martin Lindhe"]

[lib]
path = "src/lib.rs"

[dependencies]
time = "0.1"
rand = "0.4"
tempdir = "0.3"
image = "0.18"
tera = "0.11"

[dev-dependencies]
criterion = "0.1"
curl = "0.4"

[[bench]]
name = "cpu"
harness = false

[workspace]
members = [ "debugger" ]
