[package]
name = "x86emu"
version = "0.1.0"
authors = ["name"]

[dependencies]
difference = "1.0"
colog = "0.1"
log = "0.3"
time = "0.1"
rand = "0.3"
image = "0.12"

# orbtk deps:
orbtk = "0.2"


[profile.release]
debug = true
