[package]
name = "x86emu"
version = "0.1.0"
authors = ["Martin Lindhe"]

[dependencies]
difference = "1.0"
colog = "0.1"
log = "0.3"
time = "0.1"
rand = "0.3"
gdk = "0.6"
gdk-pixbuf = "0.2"
cairo-rs = "0.2"
raster = "0.2"

[dependencies.gtk]
version = "0.2"
features = ["v3_10"]



[profile.release]
debug = true
