[package]
name = "dustbox"
version = "0.1.0"
authors = ["Martin Lindhe"]

[lib]
path = "src/lib.rs"

[dependencies]
time = "0.1"
rand = "0.4"
tempdir = "0.3"
image = "0.18"
tera = "0.11"
quick-error = "1.2"
simple-error = "0.1"
pretty_assertions = "0.5"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "cpu"
harness = false

[workspace]
members = [ "debugger", "fuzzer" ]
