[package]
name = "x86emu"
version = "0.1.0"
authors = ["name"]

[dependencies]
difference = "1.0"
colog = { git = "https://github.com/chrivers/rust-colog" }
log = "*"
time = "0.1"
gfx = "0.14"
glutin ="*"
gfx_window_glutin = "*"

[profile.release]
debug = true
