[package]
name = "x86emu"
version = "0.1.0"
authors = ["name"]

[dependencies]
difference = "1.0"
colog = { git = "https://github.com/chrivers/rust-colog" }
log = "*"
time = "0.1"
gfx = "0.14"
piston_window = "0.64"
image = "0.12"
gfx_device_gl = "0.13"
vecmath = "0.3"

[profile.release]
debug = true
