[package]
name = "x86emu"
version = "0.1.0"
authors = ["name"]

[dependencies]
difference = "1.0"
colog = { git = "https://github.com/chrivers/rust-colog" }
log = "*"
time = "0.1"
image = "0.12"
rand = "0.3"
find_folder = "0.3"

# glutin deps:
gfx = "0.14"
gfx_core = "0.6"
gfx_window_glutin = "0.14"
glutin = "0.7"

# conrod deps:
#piston_window = "0.63"
glium = { version = "0.16.0" }
winit = { version = "0.5.9" }
conrod = { version = "*", features = ["glium", "winit"] }



[profile.release]
debug = true
