[package]
name = "dustbox_fuzzer"
version = "0.1.0"
authors = ["Martin Lindhe"]

[lib]
path = "src/lib.rs"

[dependencies]
curl = "0.4"
dustbox = { path = "../dustbox" }
rand = "0.7"
rand_xorshift = "0.2"
tempdir = "0.3"
tera = { version = "1.0", default-features = false }
