[package]
name = "dustbox_fuzzer"
version = "0.1.0"
authors = ["Martin Lindhe"]

[lib]
path = "src/lib.rs"

[dependencies]
curl = "0.4"
dustbox = { path = "../" }
rand = "0.6"
rand_xorshift = "0.1"
tempdir = "0.3"
tera = "0.11"
