[package]
name = "dustbox_disassembler"
version = "0.1.0"
authors = ["Martin Lindhe"]

[[bin]]
name = "dustbox-disasm"
path = "src/disassembler-main.rs"

[dependencies]
clap = "2.32"
dustbox = { path = "../" }
