[package]
name = "dustbox_disassembler"
version = "0.1.0"
authors = ["Martin Lindhe"]

[[bin]]
name = "dustbox-disasm"
path = "src/disassembler-main.rs"

[dependencies]
chrono = "0.4"
clap = "2.33"
dustbox = { path = "../" }
