[package]
name = "debugger"
version = "0.1.0"
authors = ["Martin Lindhe"]
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
cairo-rs = "0.8"
clap = "2.33"
dustbox = { path = "../dustbox" }
gdk = "0.12"
gdk-pixbuf = "0.8"
gtk = { version = "0.8", features = [ "v3_16" ] }
