[package]
name = "dustbox_debugger"
version = "0.1.0"
authors = ["Martin Lindhe"]

[lib]
path = "src/lib.rs"

[dependencies]
gdk = "0.8"
gdk-pixbuf = "0.4"
cairo-rs = "0.4"
dustbox = { path = "../" }

[dependencies.gtk]
version = "0.4"
features = ["v3_10"]
