[package]
name = "dustbox_debugger"
version = "0.1.0"
authors = ["Martin Lindhe"]

[lib]
path = "src/lib.rs"

[dependencies]
cairo-rs = "0.7"
dustbox = { path = "../" }
gdk = "0.11"
gdk-pixbuf = "0.7"

[dependencies.gtk]
version = "0.7"
features = ["v3_16"]
